### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by nmeyvis** [GHFear/AESDumpster#1]
Hi, I downloaded the AESDumpster.exe and dragged the game's Shipping.exe on it. The CLI output says "Done!" with no other feedback. Are the results outputted to a directory that I'm not seeing? Did the process fail with no feedback? The game isn't steam published but I'm also unsure if the game's exe has other DRM.

**Comment by nmeyvis** [comment]
Looks like I can drag any file type and it output says "Done!"

**Comment by GHFear** [comment]
> Looks like I can drag any file type and the output says "Done!"

Yep, you can scan any file.
Upload the exe to MEGA and send the link to it.
I will take a look at it tonight or tomorrow.

**Comment by nol3w** [comment]
I had the same issue because of Steamstub DRM. You can try unpacking the .exe using https://github.com/atom0s/Steamless and pass the unpacked exe to AESDumpster

**Comment by MagicTurtle37** [comment]
Hello, I also got a file and the only output is "Done!" not sure if it's the right one but it's the only exe I can find and the unreal engine version seems to be 5.4.3.0.
https://mega.nz/file/pPFTXY5T#qczwj6DCDOKtVZq2nGAXfJMTKIHEdL9RYrZBjU69gEU (here is the exe)

**Comment by GHFear** [comment]
> Hello, I also got a file and the only output is "Done!" not sure if it's the right one but it's the only exe I can find and the unreal engine version seems to be 5.4.3.0. "https://mega.nz/file/pPFTXY5T#qczwj6DCDOKtVZq2nGAXfJMTKIHEdL9RYrZBjU69gEU" this is the exe

There is another exe in the folder "Binaries/Win64"
I need that one :)

**Comment by MagicTurtle37** [comment]
Here you go "https://mega.nz/file/8f1HiboJ#k2sl-xEADH6y2_AqFGRT_aCbZULMQRndvx7YX8KPTEU"
Was able to get some keys out from it but they did not seem to do much for me

**Comment by GHFear** [comment]
> Here you go "https://mega.nz/file/8f1HiboJ#k2sl-xEADH6y2_AqFGRT_aCbZULMQRndvx7YX8KPTEU" Was able to get some keys out from it but they did not seem to do much for me

Try this: 0xDFA62F3EE8304BBF7A6E153F2F88203F823C47BF0A690D3D4793FB3EFA624F3F

**Comment by MagicTurtle37** [comment]
Seems like I just forgot to add the 0x in the beginning, but that solved everything for me. 
Thanks a lot for the help!

**Comment by GHFear** [comment]
> Seems like I just forgot to add the 0x in the beginning, but that solved everything for me. Thanks a lot for the help!

Which key was it?

**Comment by MagicTurtle37** [comment]
0x0680378ba2b15c9690aade0e70883ac48a5fc7da1ff315e89479c96c4233ce30

**Comment by GHFear** [comment]
> 0x0680378ba2b15c9690aade0e70883ac48a5fc7da1ff315e89479c96c4233ce30

Nice!
I fixed the program, so now it shows type 2 keys as well.
Also added so it adds 0x in front of the key automatically. :)
Will upload the updated source and binary in 5 minutes.
