### ISSUE TITLE
Given keys don't seem correct?

### ISSUE THREAD

**Issue by AllTradesGames** [GHFear/AESDumpster#3]
Built the solution and dropped the shipping exe onto the /x64/Debug/AESDumpster.exe. Seemed to run fine and returned several potential keys. One had a high level of entropy. Added '0x' to each key and attempted to use them with FModel. None of them did the trick. Can I send you a link to the shipping exe to take a look?

**Comment by GHFear** [comment]
Download the 1.1 release build instead.
If that doesn't work, upload exe.

**Comment by AllTradesGames** [comment]
Thanks, this version gave a few more promising results, but none of them worked in FModel. I've uploaded the game and added you on discord.

**Comment by GHFear** [comment]
Issue is fixed in 1.2.2 release build
