### ISSUE TITLE
No keys being shown

### ISSUE THREAD

**Issue by 4345dgfsd** [GHFear/AESDumpster#5]
I do exactly as the .exe says, i drag and drop the exe file of the game.
In the end i just get a message that says "Done!" Without it giving me any keys?
The game is: Voices of The Void, unreal engine version is: 4.27

What's the fix here?

**Comment by GHFear** [comment]
> I do exactly as the .exe says, i drag and drop the exe file of the game. In the end i just get a message that says "Done!" Without it giving me any keys? The game is: Voices of The Void, unreal engine version is: 4.27
> 
> What's the fix here?

The game Pak isn't encrypted.
You don't need a key to open the Pak file in Fmodel.

/Adam

**Comment by 4345dgfsd** [comment]
Ah, okay, thank you very much.
